# Generated by Django 5.2.16 on 2026-07-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
